name: Build DriverContainer image

description: This action builds a DriverContainer image for CI

inputs:
  kernel-version:
    required: true
    description: The kernel version against which the module should be built

runs:
  using: composite

  steps:
    - name: Build the kernel module
      run: make KERNEL_SRC_DIR="/usr/src/linux-headers-${{ inputs.kernel-version }}"
      working-directory: ci/kmm-kmod
      shell: bash

    - name: Build the image
      run: docker build -t kmm-kmod:local --build-arg=KERNEL_VERSION=${{ inputs.kernel-version }} ci/kmm-kmod
      shell: bash

    - name: Export the image
      run: docker save -o kmm-kmod_local.tar kmm-kmod:local
      shell: bash
