---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-minikube-registry-alias
spec:
  template:
    spec:
      containers:
        - name: wait-minikube-registry-alias
          image: alpine
          command: [nslookup, registry.minikube]
      restartPolicy: OnFailure
