---
apiVersion: v1
kind: Service
metadata:
  name: registry-nodeport
  namespace: kube-system
spec:
  selector:
    actual-registry: 'true'
    kubernetes.io/minikube-addons: registry
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort
